services:
  - type: web
    name: youtube-downloader
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_URL
        value: https://sebagutierrezf.github.io
      - key: YOUTUBE_API_KEY
        sync: false 